### ISSUE TITLE
AdminClient.DeleteTable giving an error

### ISSUE THREAD

**Issue by jonbonazza** [tsuna/gohbase#39]
Hello, back again. =)
Almost everything is working great for me so far, however I currently have an issue with the admin client.

I created a new AdminClient using ```gohbase.NewAdminClient``` and tried to use it to drop a table using AdminClient.DeleteTable, which (as I sort of expected it would), complain about the table not being disabled. That's fine, I first disable the table, which works, then I immediately call DeleteTable and this time it fails with an entirely different error that I cannot seem to figure out:
```
HBase Java exception org.apache.hadoop.hbase.DoNotRetryIOException:
<IP redacted> is unable to read call parameter from client <IP redacted>; java.lang.UnsupportedOperationException: getProcedureResult
```
We are using Cloudera Hbase 5.6.x.
Any ideas what is going on here? So far, this is the only function that is failing.

**Comment by jonbonazza** [comment]
Actually, looking more into this, it seems that all AdminClient functions return this error after completing their job. So even when I just call Disable, I get this error despite the table being disabled. Similarly, if I first disable the table from the hbase shell and then call Delete, I get this error, but the table is actually deleted.

**Comment by Timoha** [comment]
So the way AdminClient methods works is as follows:
Send a request to start procedure for creating/enabling/deleting/disabling table to HBase Master, and then probe the procedure it with the returned ID until it completes. The reason why the operation are still successful even though they return an error is because the procedure eventually completes, it's just the check for it fails.

From the looks, hbase that you are using doesn't recognize `getProcedureResult` request, not sure why.

**Comment by jonbonazza** [comment]
@Timoha I see. Wouldn't surprise me... we have an... unorthodox setup here (Cloudera HBase running on Gentoo >.>). I'm going to close this for now, as seems to be environment related, rather than an issue with the code. I'll reopen if I find anything new. Thanks!
