### ISSUE TITLE
Limit number of columns per row

### ISSUE THREAD

**Issue by dougklein** [tsuna/gohbase#40]
I have a requirement to the limit number of columns returned from very wide rows. 

I have forked this project and I am able to make this work by exposing the StoreLimit property which already exists in the Scan and Get structs.

Before I continue on with this, is there some reason why  StoreLimit and StoreOffset aren't already accessible?

**Comment by Timoha** [comment]
> is there some reason why StoreLimit and StoreOffset aren't already accessible?

no reason other than no one need the feature :)
Feel free to send the pull request with your implementation (with integration tests), would be happy to see your contribution. Remember to sign licensing agreement first: https://github.com/tsuna/gohbase#contributing

**Comment by Timoha** [comment]
Hello, 

I improved the api of Scan to be able to get a row a time and added an option to ask for partial rows in order to resolve a potential OOM issue if a row is too big: https://github.com/tsuna/gohbase/commit/45ae8893ad247be1559746a985f837db8bc1cdc5

When you create a scan, you can pass [this option](https://godoc.org/github.com/tsuna/gohbase/hrpc#AllowPartialResults) to tell regionservers to return partial rows so that they don't run out of memory. Not sure if the returned results are going to be small enough for your client. Would this option be enough for your case?

**Comment by dougklein** [comment]
Sorry I missed your last question. The improved Scan API is very useful for us for some of our use cases. Our immediate problems was with gets.

We store events against a user key in a single column family and use the column qualifiers as keys to the event - sorted in descending order. We need to be able to limit the number of columns returned on any given request as some users have many thousands of events even when applying a timerange - and we don't want them all; just the latest n number very quickly.

I went ahead and added the functionality to both scans and gets while I had my fingers in there since the attributes already existed in the Get and Scan structs in Client.pb.go.
